blueprint:
  name: Stream Camera to TV
  description: |
    Stream a camera to Android TV using a HA TV Dashboard notification.
    Blueprint version 1.0.1
  domain: script
  author: nodinosaur / George
  source_url: https://github.com/nodinosaur/ha_tv_dashboard_blueprints/blob/main/stream_camera.yaml
  homeassistant:
    min_version: "2024.6.0"

  input:
    notify_service:
      name: Notification Service
      description: >
        Enter the notify service (auto-complete works).
        Example: notify.mobile_app_lounge_tv
      default: notify.notify
      selector:
        text: {}    
        

    camera_config:
      name: Camera config
      icon: hass:cctv
      collapsed: true
      input:
        camera_entity:
          name: Camera Entity
          selector:
            entity:
              domain: camera

        camera_name:
          name: Camera Name
          default: ""
          selector:
            text: {}

        format:
          name: Stream Format
          description: |
            Specify the video format. 
            - HLS feeds are generated by Home Assistant for some cameras.
            - RTSP for direct video feed.
            - WebRTC feeds generated by go2rtc. 
          default: hls
          selector:
            select:
              options:
                - label: "HLS - Built into HA for some cameras"
                  value: "hls"
                - label: "RTSP - Enter URL below"
                  value: "rtsp"
                - label: "WebRTC - Enter URL below"
                  value: "webrtc"

        camera_feed:
          name: Video source URL
          description: |
            Used only when Source type = RTSP or WebRTC. 
            i.e.
            - rtsp://user:pass@host:554/path
            - http://<go2rtc:1984>/stream.html?src=driveway_cam&mode=webrtc
          default: ""
          selector:
            text: {}

        image:
          description: |
            Path to camera snapshot image "/local/… or http://… ". 
            Assets available here - 
            https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Graphical-assets
          name: Preview Image URL / Path
          default: ""
          selector:
            text: {}


    decoration_prefs:
      name: Decoration
      icon: hass:party-popper
      collapsed: true
      input:
        title:
          name: Title
          default: ""
          selector:
            text: {}

        message:
          name: Message
          default: ""
          selector:
            text: {}

        icon:
          description: |
            Specify icon to signify which camera was used. 
            Assets available here - 
            https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Graphical-assets
          name: Icon URL / Path
          default: ""
          selector:
            text: {}



    notification_prefs:
      name: Frame preferences
      icon: hass:message-flash-outline
      collapsed: true
      input:
        filter:
          name: Filter
          description: |
            Group notifications by filter types. 
            i.e. person, doorbell, etc
          default: ""
          selector:
            text: {}

        position:
          name: Position
          description: |
            Choose the screen corner where you want the camera pop-up overlay to appear.
          default: bottom-right
          selector:
            select:
              options:
                - label: "Top left"
                  value: "top-left"
                - label: "Top right"
                  value: "top-right"
                - label: "Bottom left"
                  value: "bottom-left"
                - label: "Bottom right"
                  value: "bottom-right"

        duration:
          name: Duration
          description: |
            Specify the duration the notification displays in seconds.
          default: 3
          selector:
            number:
              min: 3
              max: 300
              unit_of_measurement: seconds

        fontsize:
          name: Font Size
          description: |
            The size of the title and message text.
          default: medium
          selector:
            select:
              options:
                - label: "Small"
                  value: "small"
                - label: "Medium"
                  value: "medium"
                - label: "Large"
                  value: "large"
                - label: "Max"
                  value: "max"

        # 2. Fixed Width to use Strings
        width:
          name: Width (px)
          description: |
            The width of the camera pop-up notification.
          default: "240"
          selector:
            select:
              options:
                - "120"
                - "240"
                - "320"
                - "480"
                - "540"

        # 3. Fixed Transparency to use Strings
        transparency:
          description: |
            The opacity of the camera pop-up notification.
          name: Transparency
          default: "5"
          selector:
            select:
              options:
                - label: "100%"
                  value: "5"
                - label: "80%"
                  value: "1"
                - label: "75%"
                  value: "4"
                - label: "50%"
                  value: "3"
                - label: "25%"
                  value: "2"

        color:
          name: Background Color
          description: |
            The colour of camera pop-up notification frame.
          default: [40, 44, 53]
          selector:
            color_rgb: {}


        show_frame:
          name: Show Frame
          description: |
            Specify if the frame shows.
          default: true
          selector:
            boolean: {}

variables:
  notify_service: !input notify_service
  title: !input title
  message: !input message
  camera_entity: !input camera_entity
  camera_name: !input camera_name
  format: !input format
  image: !input image
  icon: !input icon
  filter: !input filter
  position: !input position
  duration: !input duration
  fontsize: !input fontsize
  width: !input width
  transparency: !input transparency
  color: !input color
  show_frame: !input show_frame

sequence:
  - action: !input notify_service
    data:
      title: "{{ title if title | trim else state_attr(camera_entity, 'friendly_name') }}"
      message: "{{ message }}"
      data:
        notif_type: stream
        entity_id: "{{ camera_entity }}"
        camera_name: >-
          {{ camera_name if camera_name | trim
            else state_attr(camera_entity, 'friendly_name') }}
        video: "{{ format }}"
        image: "{{ image if image | trim else none }}"
        icon: "{{ icon if icon | trim else none }}"
        filter: "{{ filter if filter | trim else none }}"
        config:
          position: "{{ position }}"
          duration: "{{ duration }}"
          fontsize: "{{ fontsize }}"
          width: "{{ width | int }}"
          transparency: "{{ transparency | int }}"
          color: "{{ '#%02x%02x%02x' | format(color[0], color[1], color[2]) }}"
          show_frame: "{{ show_frame }}"