blueprint:
  name: Calendar Today's Events to TV
  description: |
    Display today's calendar events on Android TV using HA TV Dashboard notification.
    Choose your preferred calendar entity.
    Requires (HA TV Dashboard)[https://play.google.com/store/apps/details?id=io.homeassistant.companion.androidtv] 2026.2.1 (139) or newer.
    Blueprint version 1.0.0
  domain: script
  author: nodinosaur / George
  source_url: https://github.com/nodinosaur/ha_tv_dashboard_blueprints/blob/main/script/calendar_todays_events_to_tv.yaml
  homeassistant:
    min_version: "2024.6.0"

  input:
    notify_service:
      name: Notification Service
      description: >
        Enter the notify service (auto-complete works).
        Example: notify.mobile_app_lounge_tv
      default: notify.notify
      selector:
        text: {}

    calendar_config:
      name: Calendar Configuration
      icon: mdi:calendar
      collapsed: true
      input:
        calendar_entity:
          name: Calendar Entity
          description: |
            Select your calendar entity.
            Examples: calendar.local, calendar.family, calendar.work
          selector:
            entity:
              domain: calendar

        title:
          name: Title
          description: |
            Title displayed on the calendar notification.
          default: "Today's Calendar"
          selector:
            text: {}

variables:
  notify_service: !input notify_service
  calendar_entity: !input calendar_entity
  title: !input title

sequence:
  - action: !input notify_service
    data:
      title: "{{ title }}"
      message: ""
      data:
        notif_type: calendar
        calendar:
          message: "{{ state_attr(calendar_entity, 'message') }}"
          description: "{{ state_attr(calendar_entity, 'description') }}"
          start_time: "{{ state_attr(calendar_entity, 'start_time') }}"
